### ISSUE TITLE
.class files

### ISSUE THREAD

**Issue by costimuraru** [Apress/java-game-dev-LibGDX#1]
Nice job on the book! It's really cool and the sample projects found here are awesome!
I've noticed the presence of the `.class` files as well. This seem a bit redundant here, and makes it a bit harder to navigate the project. Is there a specific reason why you chose to store them in git, or can we update .gitignore to ignore all `.class` files?
Keep up the good work!

**Comment by stemkoski** [comment]
You are correct; the .class files can all safely be ignored.
